# Generated by Django 2.1.7 on 2019-02-20 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companiesapp', '0002_asanimza_companycontracts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=255, verbose_name='Qeydler')),
                ('doc_date', models.DateField()),
                ('doc_expr_date', models.DateField()),
                ('doc_send_date', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Hazirlandi'), (2, 'Gonderen imzaladi'), (3, 'Qebul eden imzaladi'), (4, 'Qebul eden imtina etdi'), (5, 'Vaxti bitdi')], default=1)),
                ('doc_file', models.FileField(upload_to='docs')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_doc_set', to='companiesapp.company')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sened_doc_set', to='companiesapp.company')),
            ],
        ),
    ]
